export enum EConfig {
  YOUTUBE = 'YOUTUBE',
  ZALO = 'ZALO',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  WEBSITE_URL = 'WEBSITE_URL',
  SITE_NAME = 'SITE_NAME',
  ABOUT_US = 'ABOUT_US',
  GREETING_DETAIL_ARTICLE = 'GREETING_DETAIL_ARTICLE',
  SLOGAN_BOTTOM = 'SLOGAN_BOTTOM',
  SLOGAN_TOP = 'SLOGAN_TOP'
}
